### ISSUE TITLE
Ejemplo de ejecución

### ISSUE THREAD

**Issue by nicoguaro** [MrAgeo/mechwave#1]
¿Existe algún ejemplo que incluya una malla para ver el código ejecutándose?

**Comment by MrAgeo** [comment]
Hola Nicolás!

Sí, acabamos de subir la misma malla que usamos en el video de explicación de este proyecto (el cual puedes encontrarlo en [https://www.youtube.com/watch?v=lg9X_b6Rx4o](https://www.youtube.com/watch?v=lg9X_b6Rx4o)). La carpeta de ejemplos `mesh_examples` está en `/base`.

Si tienes alguna otra duda, estaremos atentos!
